### ISSUE TITLE
Error with mcrouter and xmemcached

### ISSUE THREAD

**Issue by tomasAlabes** [sixhours-team/memcached-spring-boot#106] opened 2020-10-12 12:54 UTC
I'm having the exact same error as #92:

```
io.sixhours.memcached.cache.MemcachedOperationException: Failed to touch key
at io.sixhours.memcached.cache.XMemcachedClient.touch(XMemcachedClient.java:74)
at io.sixhours.memcached.cache.MemcachedCache.put(MemcachedCache.java:109)
[...]
Caused by: net.rubyeye.xmemcached.exception.MemcachedServerException: unexpected result mc_res_unknown (0) for touch,key=my_prefix#:something:namespace
at net.rubyeye.xmemcached.command.Command.decodeError(Command.java:259)
at net.rubyeye.xmemcached.command.Command.decodeError(Command.java:274)
at net.rubyeye.xmemcached.command.text.TextTouchCommand.decode(TextTouchCommand.java:76)
at net.rubyeye.xmemcached.codec.MemcachedDecoder.decode0(MemcachedDecoder.java:55)
at net.rubyeye.xmemcached.codec.MemcachedDecoder.decode(MemcachedDecoder.java:50)
at com.google.code.yanf4j.nio.impl.NioTCPSession.decode(NioTCPSession.java:281)
at com.google.code.yanf4j.nio.impl.NioTCPSession.decodeAndDispatch(NioTCPSession.java:223)
at com.google.code.yanf4j.nio.impl.NioTCPSession.readFromBuffer(NioTCPSession.java:194)
at com.google.code.yanf4j.nio.impl.AbstractNioSession.onRead(AbstractNioSession.java:184)
at com.google.code.yanf4j.nio.impl.AbstractNioSession.onEvent(AbstractNioSession.java:324)
at com.google.code.yanf4j.nio.impl.SocketChannelController.dispatchReadEvent(SocketChannelController.java:54)
at com.google.code.yanf4j.nio.impl.NioController.onRead(NioController.java:150)
at com.google.code.yanf4j.nio.impl.Reactor.dispatchEvent(Reactor.java:310)
at com.google.code.yanf4j.nio.impl.Reactor.run(Reactor.java:177)
```

In my case the mcrouter config is:

```
 "pools": {
    "Process": {
      "servers": [...]
    }
  },
 "route": {
    "type": "PrefixSelectorRoute",
    "policies": {
      "my_prefix": {
        "type": "OperationSelectorRoute",
        "operation_policies": {
          "add": "AllSyncRoute|Pool|Process",
          "delete": "AllSyncRoute|Pool|Process",
          "get": {
            "type": "MissFailoverRoute",
            "return_best_on_error": true,
            "children": [{
              "type": "PoolRoute",
              "pool": "Process"
            }]
          },
          "set": "AllSyncRoute|Pool|Process",
          "incr": "AllSyncRoute|Pool|Process",
          "decr": "AllSyncRoute|Pool|Process"
        }
      }
```

I can't modify this configuration so the only chance I have is to try with `spymemcached`.
Is it possible to provide the ability to pick the backing lib from the classpath? It would give us the flexibility to choose.

**Comment by igorbolic** [comment] 2020-10-12 13:10
We'll look into this as priority i.e. to have an option to select from different Memcached client implementations i.e. XMemcached vs SpyMemcached. Thanx for reporting this 👍

**Comment by tomasAlabes** [comment] 2020-10-12 14:38
Thank you!
As FYI, with `spymemcached` it's *kind of working*. It fails and then reconnects and seems to work. All in the same command.
With `xmemcached` the 1st time doesn't work at all, but the 2nd time works (until entry is removed from mc I believe).

```
OperationException: SERVER: SERVER_ERROR unexpected result mc_res_unknown (0) for touch
net.spy.memcached.protocol.BaseOperationImpl.handleError(BaseOperationImpl.java:192)
net.spy.memcached.protocol.ascii.OperationImpl.readFromBuffer(OperationImpl.java:152)
net.spy.memcached.MemcachedConnection.readBufferAndLogMetrics(MemcachedConnection.java:1064)
net.spy.memcached.MemcachedConnection.handleReads(MemcachedConnection.java:1043)
net.spy.memcached.MemcachedConnection.handleReadsAndWrites(MemcachedConnection.java:923)
net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:886)
net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:531)
net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1685)
WARN net.spy.memcached.MemcachedConnection:  Closing, and reopening {QA sa=/10.96.105.191:11211, #Rops=1, #Wops=0, #iq=0, topRop=Cmd: touch key: my_prefix#:something:namespace exp: 60, topWop=null, toWrite=0, interested=1}, attempt 0.
WARN net.spy.memcached.protocol.ascii.AsciiMemcachedNodeImpl:  Discarding partially completed op: Cmd: touch key: my_prefix#:something:namespace exp: 60
```

**Comment by tomasAlabes** [comment] 2020-10-16 16:32
@igorbolic do you have some ETA on this?

**Comment by igorbolic** [comment] 2020-10-16 17:46
I was able to reproduce the issue locally.

It appears the [mcrouter](https://github.com/facebook/mcrouter) settings are missing `touch` operation.  For the cache region namespace updates we are using the Memcached `touch` command. Therefore, I believe adding `touch` setting to **mcrouter** config should remedy the issue you are experiencing i.e. if you set your operation polices to something like below (additional to your setting I've added the `touch` operation setting at the end):

```json
{
  "add": "AllSyncRoute|Pool|Process",
  "delete": "AllSyncRoute|Pool|Process",
  "get": {
    "type": "MissFailoverRoute",
    "return_best_on_error": true,
    "children": [
      {
        "type": "PoolRoute",
        "pool": "Process"
      }
    ]
  },
  "set": "AllSyncRoute|Pool|Process",
  "incr": "AllSyncRoute|Pool|Process",
  "decr": "AllSyncRoute|Pool|Process",
  "touch": "AllSyncRoute|Pool|Process"
}
```

Do give it a try and let me know if it works for you

**Comment by tomasAlabes** [comment] 2020-10-16 20:59
Yes, that is actually how I fixed it. But having the ability of changing the native client is useful for extending or changing it's capabilities too.
At least that is my current problem (I'm trying to add circuit breaking to the calls).

-------- Original Message --------

**Comment by igorbolic** [comment] 2020-10-17 08:23
I agree that it could be useful to have such option. I've created a new issue #107  for this.
I'm closing this issue since it has been resolved with **mcrouter** configuration.

**Closed by igorbolic** 2020-10-17 08:23 UTC
